version: "3.8"

services:
  api:
    container_name: clean-architecture-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    volumes:
      - ./src/Callcenter.Backend.Api/Callcenter.Backend.sqlite:/app/Callcenter.Backend.sqlite
  postgres:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
